/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/model.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="db0c70578e5840fd93f266aa058e6c3dfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Radial_Engine"
                  position={[0, -15.84, 0]}
                  rotation={[0, 0, Math.PI]}
                >
                  <group name="Cylinder_1">
                    <group name="Lid1" position={[47.38, -31.56, -13.38]}>
                      <mesh
                        name="Lid1_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Lid1_Radial_Engine_To_Skfb_Orange_Mat_0.geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Plate" position={[17, -16.2, 0]}>
                      <mesh
                        name="Plate_Radial_Engine_To_Skfb_Grey_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Plate_Radial_Engine_To_Skfb_Grey_Mat_0.geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Grey_Mat}
                      />
                    </group>
                    <group name="Ring" position={[18, -17.9, 0]}>
                      <mesh
                        name="Ring_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Ring_Radial_Engine_To_Skfb_Orange_Mat_0.geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Bolts">
                      <group name="Bolt002" position={[6.89, 23.05, -11.51]}>
                        <mesh
                          name="Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt1" position={[52.3, -3.7, 7.74]}>
                        <mesh
                          name="Bolt1_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt1_Radial_Engine_To_Skfb_Bolt_Mat_0
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt2" position={[52.3, -3.7, -7.95]}>
                        <mesh
                          name="Bolt2_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt2_Radial_Engine_To_Skfb_Bolt_Mat_0
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt3" position={[52.3, -28.5, 12.72]}>
                        <mesh
                          name="Bolt3_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt3_Radial_Engine_To_Skfb_Bolt_Mat_0
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt4" position={[52.3, -28.5, -13.11]}>
                        <mesh
                          name="Bolt4_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt4_Radial_Engine_To_Skfb_Bolt_Mat_0
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group
                        name="Nut002"
                        position={[6.6, -2.4, -11.43]}
                        rotation={[0, 0.52, 0]}
                      >
                        <mesh
                          name="Nut_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut1" position={[12.53, -3.4, 7.82]}>
                        <mesh
                          name="Nut1_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut1_Radial_Engine_To_Skfb_Bolt_Mat_0.geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut2" position={[12.53, -3.4, -7.87]}>
                        <mesh
                          name="Nut2_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut2_Radial_Engine_To_Skfb_Bolt_Mat_0.geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut3" position={[12.53, -28.2, 12.79]}>
                        <mesh
                          name="Nut3_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut3_Radial_Engine_To_Skfb_Bolt_Mat_0.geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut4" position={[12.53, -28.2, -13.03]}>
                        <mesh
                          name="Nut4_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut4_Radial_Engine_To_Skfb_Bolt_Mat_0.geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cylinder_2"
                    rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
                  >
                    <group name="Lid" position={[41.35, -16.2, 0]}>
                      <mesh
                        name="Lid_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Lid_Radial_Engine_To_Skfb_Orange_Mat_0.geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Plate001" position={[17, -16.2, 0]}>
                      <mesh
                        name="Plate_Radial_Engine_To_Skfb_Grey_Mat_0001"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Plate_Radial_Engine_To_Skfb_Grey_Mat_0001
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Grey_Mat}
                      />
                    </group>
                    <group name="Ring001" position={[18, -17.9, 0]}>
                      <mesh
                        name="Ring_Radial_Engine_To_Skfb_Orange_Mat_0001"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Ring_Radial_Engine_To_Skfb_Orange_Mat_0001
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Bolts001">
                      <group name="Bolt003" position={[6.89, 23.05, -11.51]}>
                        <mesh
                          name="Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0003"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0003
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt1001" position={[41.44, -3.7, 7.74]}>
                        <mesh
                          name="Bolt1_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt1_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt2001" position={[41.44, -3.7, -7.95]}>
                        <mesh
                          name="Bolt2_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt2_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt3001" position={[41.44, -28.5, 12.72]}>
                        <mesh
                          name="Bolt3_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt3_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt4001" position={[41.44, -28.5, -13.11]}>
                        <mesh
                          name="Bolt4_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt4_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group
                        name="Nut003"
                        position={[6.6, -2.4, -11.43]}
                        rotation={[0, 0.52, 0]}
                      >
                        <mesh
                          name="Nut_Radial_Engine_To_Skfb_Bolt_Mat_0003"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut_Radial_Engine_To_Skfb_Bolt_Mat_0003
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut1001" position={[12.53, -3.4, 7.82]}>
                        <mesh
                          name="Nut1_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut1_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut2001" position={[12.53, -3.4, -7.87]}>
                        <mesh
                          name="Nut2_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut2_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut3001" position={[12.53, -28.2, 12.79]}>
                        <mesh
                          name="Nut3_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut3_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut4001" position={[12.53, -28.2, -13.03]}>
                        <mesh
                          name="Nut4_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut4_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cylinder_3"
                    rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
                  >
                    <group name="Lid001" position={[41.35, -16.2, 0]}>
                      <mesh
                        name="Lid_Radial_Engine_To_Skfb_Orange_Mat_0001"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Lid_Radial_Engine_To_Skfb_Orange_Mat_0001
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Ring002" position={[18, -17.9, 0]}>
                      <mesh
                        name="Ring_Radial_Engine_To_Skfb_Orange_Mat_0002"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Ring_Radial_Engine_To_Skfb_Orange_Mat_0002
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Bolts002">
                      <group name="Bolt004" position={[6.89, 23.05, -11.51]}>
                        <mesh
                          name="Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0004"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0004
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt1002" position={[41.44, -3.7, 7.74]}>
                        <mesh
                          name="Bolt1_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt1_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt2002" position={[41.44, -3.7, -7.95]}>
                        <mesh
                          name="Bolt2_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt2_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt3002" position={[41.44, -28.5, 12.72]}>
                        <mesh
                          name="Bolt3_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt3_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Bolt4002" position={[41.44, -28.5, -13.11]}>
                        <mesh
                          name="Bolt4_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt4_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group
                        name="Nut004"
                        position={[6.6, -2.4, -11.43]}
                        rotation={[0, 0.52, 0]}
                      >
                        <mesh
                          name="Nut_Radial_Engine_To_Skfb_Bolt_Mat_0004"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut_Radial_Engine_To_Skfb_Bolt_Mat_0004
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut1002" position={[12.53, -3.4, 7.82]}>
                        <mesh
                          name="Nut1_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut1_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut2002" position={[12.53, -3.4, -7.87]}>
                        <mesh
                          name="Nut2_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut2_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut3002" position={[12.53, -28.2, 12.79]}>
                        <mesh
                          name="Nut3_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut3_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut4002" position={[12.53, -28.2, -13.03]}>
                        <mesh
                          name="Nut4_Radial_Engine_To_Skfb_Bolt_Mat_0002"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut4_Radial_Engine_To_Skfb_Bolt_Mat_0002
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                    </group>
                    <group name="Plate002" position={[17, -16.2, 0]}>
                      <mesh
                        name="Plate_Radial_Engine_To_Skfb_Grey_Mat_0002"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Plate_Radial_Engine_To_Skfb_Grey_Mat_0002
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Grey_Mat}
                      />
                    </group>
                  </group>
                  <group name="Parts_Center">
                    <group name="Bolts_BKP1">
                      <group name="Bolt" position={[-14.77, -67.4, -0.1]}>
                        <mesh
                          name="Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0.geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut" position={[-14.47, -49.51, -0.02]}>
                        <mesh
                          name="Nut_Radial_Engine_To_Skfb_Bolt_Mat_0"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut_Radial_Engine_To_Skfb_Bolt_Mat_0.geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                    </group>
                    <group name="Bolts_BKP2">
                      <group name="Bolt001" position={[7.18, -62, -13.14]}>
                        <mesh
                          name="Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Bolt_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                      <group name="Nut001" position={[7.48, -44.8, -13.06]}>
                        <mesh
                          name="Nut_Radial_Engine_To_Skfb_Bolt_Mat_0001"
                          castShadow
                          receiveShadow
                          geometry={
                            nodes.Nut_Radial_Engine_To_Skfb_Bolt_Mat_0001
                              .geometry
                          }
                          material={materials.Radial_Engine_To_Skfb_Bolt_Mat}
                        />
                      </group>
                    </group>
                    <group name="CYLINDER_FULL_MED_geom_set">
                      <group name="CYLINDER_FULL_MED">
                        <group name="transform1">
                          <group name="polySurface1" position={[0, 1.7, 0]}>
                            <mesh
                              name="polySurface1_Radial_Engine_To_Skfb_Orange_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface1_Radial_Engine_To_Skfb_Orange_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Orange_Mat
                              }
                            />
                          </group>
                          <group name="polySurface10" position={[0, -43.54, 0]}>
                            <mesh
                              name="polySurface10_Radial_Engine_To_Skfb_Grey_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface10_Radial_Engine_To_Skfb_Grey_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Grey_Mat
                              }
                            />
                          </group>
                          <group
                            name="polySurface11"
                            position={[-14.44, -55.1, 0]}
                          >
                            <mesh
                              name="polySurface11_Radial_Engine_To_Skfb_Grey_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface11_Radial_Engine_To_Skfb_Grey_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Grey_Mat
                              }
                            />
                          </group>
                          <group
                            name="polySurface12"
                            position={[7.5, -50.73, -12.99]}
                          >
                            <mesh
                              name="polySurface12_Radial_Engine_To_Skfb_Grey_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface12_Radial_Engine_To_Skfb_Grey_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Grey_Mat
                              }
                            />
                          </group>
                          <group name="polySurface14" position={[0, -4.4, 0]}>
                            <mesh
                              name="polySurface14_Radial_Engine_To_Skfb_Bolt_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface14_Radial_Engine_To_Skfb_Bolt_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Bolt_Mat
                              }
                            />
                          </group>
                          <group name="polySurface15" position={[0, -31.8, 0]}>
                            <mesh
                              name="polySurface15_Radial_Engine_To_Skfb_Bolt_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface15_Radial_Engine_To_Skfb_Bolt_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Bolt_Mat
                              }
                            />
                          </group>
                          <group
                            name="polySurface2"
                            position={[-0.88, -3.7, 0]}
                          >
                            <mesh
                              name="polySurface2_Radial_Engine_To_Skfb_Grey_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface2_Radial_Engine_To_Skfb_Grey_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Grey_Mat
                              }
                            />
                          </group>
                          <group
                            name="polySurface3"
                            position={[-3.87, 21.02, 0]}
                          >
                            <mesh
                              name="polySurface3_Radial_Engine_To_Skfb_Orange_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface3_Radial_Engine_To_Skfb_Orange_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Orange_Mat
                              }
                            />
                          </group>
                          <group
                            name="polySurface9"
                            position={[-2.2, -29.1, -3.15]}
                          >
                            <mesh
                              name="polySurface9_Radial_Engine_To_Skfb_Grey_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface9_Radial_Engine_To_Skfb_Grey_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Grey_Mat
                              }
                            />
                          </group>
                          <group
                            name="polySurface13"
                            position={[-3.1, -18.7, -1.2]}
                          >
                            <mesh
                              name="polySurface13_Radial_Engine_To_Skfb_Grey_Mat_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes
                                  .polySurface13_Radial_Engine_To_Skfb_Grey_Mat_0
                                  .geometry
                              }
                              material={
                                materials.Radial_Engine_To_Skfb_Grey_Mat
                              }
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Piston_1">
                    <group name="GloveFinger" position={[14.31, -17.9, 0]}>
                      <mesh
                        name="GloveFinger_Radial_Engine_To_Skfb_Glove_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.GloveFinger_Radial_Engine_To_Skfb_Glove_Mat_0
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Glove_Mat}
                      />
                    </group>
                    <group name="Piston" position={[1.05, -19.9, 0]}>
                      <mesh
                        name="Piston_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Piston_Radial_Engine_To_Skfb_Orange_Mat_0
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Washer_1" position={[9.7, -17.9, 0]}>
                      <mesh
                        name="Washer_1_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Washer_1_Radial_Engine_To_Skfb_Orange_Mat_0
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group name="Washer_2" position={[25.3, -17.9, 0]}>
                      <mesh
                        name="Washer_2_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Washer_2_Radial_Engine_To_Skfb_Orange_Mat_0
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                    <group
                      name="GloveFinger_NoRing"
                      position={[14.31, -17.9, 0]}
                      scale={0}
                    >
                      <mesh
                        name="GloveFinger_NoRing_Radial_Engine_To_Skfb_Glove_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .GloveFinger_NoRing_Radial_Engine_To_Skfb_Glove_Mat_0
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Glove_Mat}
                      />
                    </group>
                  </group>
                  <group
                    name="Piston_2"
                    position={[-8.17, -1.48, -6.87]}
                    rotation={[-Math.PI, 1.35, -Math.PI]}
                  >
                    <group name="polySurface4" position={[1.06, -19.9, 0]}>
                      <mesh
                        name="polySurface4_Radial_Engine_To_Skfb_Orange_Mat_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.polySurface4_Radial_Engine_To_Skfb_Orange_Mat_0
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                  </group>
                  <group
                    name="Piston_3"
                    position={[-8.15, 1.57, 7.02]}
                    rotation={[Math.PI, -1.39, Math.PI]}
                  >
                    <group name="polySurface4001" position={[1.06, -19.9, 0]}>
                      <mesh
                        name="polySurface4_Radial_Engine_To_Skfb_Orange_Mat_0001"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .polySurface4_Radial_Engine_To_Skfb_Orange_Mat_0001
                            .geometry
                        }
                        material={materials.Radial_Engine_To_Skfb_Orange_Mat}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model.glb");
